### ISSUE TITLE
Exception thrown when onWeekSelected is null

### ISSUE THREAD

**Issue by pb-iatros** [IronLad85/flutter_calendar_strip#30]
**version 1.0.7**

**actual behaviour**
When user navigates to another week (button or swipe) and function *onWeekSelected* is null, an exception is thrown

**expected behaviour**
calendar is rendered on the correct week. Define onWeekSelected as mandatory, or perform null check

**workaround until fix is available**
add `onWeekSelected: (_) => { },` on constructor

```
I/flutter ( 8219): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 8219): The following NoSuchMethodError was thrown while handling a gesture:
I/flutter ( 8219): The method 'call' was called on null.
I/flutter ( 8219): Receiver: null
I/flutter ( 8219): Tried calling: call(Instance of 'DateTime')
I/flutter ( 8219): 
I/flutter ( 8219): When the exception was thrown, this was the stack:
I/flutter ( 8219): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter ( 8219): #1      CalendarStripState.onNextRow.<anonymous closure> (package:calendar_strip/calendar_strip.dart:243:28)
I/flutter ( 8219): #2      State.setState (package:flutter/src/widgets/framework.dart:1244:30)
I/flutter ( 8219): #3      CalendarStripState.onNextRow (package:calendar_strip/calendar_strip.dart:241:5)
I/flutter ( 8219): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
I/flutter ( 8219): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
I/flutter ( 8219): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
I/flutter ( 8219): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
I/flutter ( 8219): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
I/flutter ( 8219): #9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
I/flutter ( 8219): #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
I/flutter ( 8219): #11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
I/flutter ( 8219): #12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
I/flutter ( 8219): #13     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
I/flutter ( 8219): #14     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
I/flutter ( 8219): #15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
I/flutter ( 8219): #16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
I/flutter ( 8219): #20     _invoke1 (dart:ui/hooks.dart:265:10)
I/flutter ( 8219): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
I/flutter ( 8219): (elided 3 frames from dart:async)
I/flutter ( 8219): 
I/flutter ( 8219): Handler: "onTap"
I/flutter ( 8219): Recognizer:
I/flutter ( 8219):   TapGestureRecognizer#ca14c
I/flutter ( 8219): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by IronLad85** [comment]
@pb-iatros  Ok i'll fix that
