### ISSUE TITLE
Exception thrown when widget.selectedDate is null

### ISSUE THREAD

**Issue by DevyankShaw** [IronLad85/flutter_calendar_strip#31]
Before switching to the latest version(1.0.7) there was no exception thrown and addToSwipeGesture works but after migrating to the latest version `selectedDate = getDateOnly(widget.selectedDate);` (line no: 126 of calendar_strip.dart) is throwing error and addToSwipeGesture doesn't work even if selectedDate is passed as DateTime.now(). 

## version 1.0.6
<img src="https://user-images.githubusercontent.com/47057254/98016199-b0925200-1e23-11eb-825f-3a6e3cb68750.jpeg" width="200" height="350">

## version 1.0.7
<img src="https://user-images.githubusercontent.com/47057254/98016222-b5ef9c80-1e23-11eb-9135-3f6263b23dff.jpeg" width="200" height="350">

`════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building Container(bg:
    BoxDecoration(color: Color(0xffffffff),
      boxShadow: [BoxShadow(Color(0xff1bbfc0), Offset(0.0, 1.0), 4.0,
        0.0)]
      )
  ):
The getter 'year' was called on null.
Receiver: null
Tried calling: year

The relevant error-causing widget was: 
  Container file:///E:/Flutter%20Development/Projects/student_app/lib/screens/homework_screen.dart:208:15
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      CalendarStripState.getDateOnly (package:calendar_strip/calendar_strip.dart:188:37)
#2      CalendarStripState.didUpdateWidget.<anonymous closure> (package:calendar_strip/calendar_strip.dart:126:24)
#3      State.setState (package:flutter/src/widgets/framework.dart:1244:30)
#4      CalendarStripState.didUpdateWidget (package:calendar_strip/calendar_strip.dart:125:7)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
W/yank.studentap(21250): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
A RenderFlex overflowed by 99483 pixels on the bottom.
The relevant error-causing widget was: 
  Column file:///E:/Flutter%20Development/Projects/student_app/lib/screens/homework_screen.dart:206:17
════════════════════════════════════════════════════════════════════════════════════════════════════
`

**Comment by IronLad85** [comment]
@DevyankShaw Thanks for reporting the bug. can you paste the chuck of code here. It will help me resolve the issue

**Comment by DevyankShaw** [comment]
Yah sure. Here it is:

```
Column(
            children: <Widget>[
              Container(
                  decoration: BoxDecoration(
                    color: Colors.white,
                    boxShadow: [
                      BoxShadow(
                        color: base,
                        offset: Offset(0.0, 1.0), //(x,y)
                        blurRadius: 4.0,
                      ),
                    ],
                  ),
                  child: CalendarStrip(
                    addSwipeGesture: true,
                    startDate: _startDate,
                    endDate: _endDate,
                    onDateSelected: _onSelect,
                    dateTileBuilder: _dateTileBuilder,
                    iconColor: Colors.black87,
                    monthNameWidget: _monthNameWidget,
                    containerDecoration: BoxDecoration(color: Colors.white),
                  )),
                 ..
                 .....
                 ........
                 ])
```

```
DateTime _startDate = DateTime.now().subtract(Duration(days: 30));
DateTime _endDate = DateTime.now().add(Duration(days: 0));
```


```
_onSelect(DateTime selectedDateTime) {
    setState(() {
      _isFetchingHomework = false;
    });
    print(selectedDateTime);
    _getHomework(
        startDateTime: selectedDateTime,
        endDateTime: selectedDateTime.add(Duration(days: 1)));
  }
```

```
_monthNameWidget(monthName) {
    return Container(
      child: Text(monthName,
          style: TextStyle(
              fontSize: 17,
              fontWeight: FontWeight.w600,
              color: Colors.black87,
              fontStyle: FontStyle.normal)),
      padding: EdgeInsets.only(top: 8, bottom: 4),
    );
  }
```

```
_dateTileBuilder(
      date, selectedDate, rowIndex, dayName, isDateMarked, isDateOutOfRange) {
    bool isSelectedDate = date.compareTo(selectedDate) == 0;
    Color fontColor = isDateOutOfRange ? Colors.black26 : Colors.black87;
    TextStyle normalStyle =
        TextStyle(fontSize: 17, fontWeight: FontWeight.w800, color: fontColor);
    TextStyle selectedStyle = TextStyle(
        fontSize: 17, fontWeight: FontWeight.w800, color: Colors.black87);
    TextStyle dayNameStyle = TextStyle(fontSize: 14.5, color: fontColor);
    List<Widget> _children = [
      Text(dayName, style: dayNameStyle),
      Text(date.day.toString(),
          style: !isSelectedDate ? normalStyle : selectedStyle),
    ];

    return AnimatedContainer(
      duration: Duration(milliseconds: 150),
      alignment: Alignment.center,
      padding: EdgeInsets.only(top: 8, left: 5, right: 5, bottom: 5),
      decoration: BoxDecoration(
        color: !isSelectedDate ? Colors.transparent : base,
        borderRadius: BorderRadius.all(Radius.circular(60)),
      ),
      child: Column(
        children: _children,
      ),
    );
  }
```

@IronLad85 I hope this will help you to resolve the issue

**Comment by mobinshaik999** [comment]
` setState(() {
        if(widget.selectedDate!=null){
          selectedDate = getDateOnly(widget.selectedDate);
        }
      });`

wrapped with a if condition  in didUpdateWidget(CalendarStrip oldWidget)  method  at line 125 , this fixed error
